### ISSUE TITLE
Kubernetes yaml

### ISSUE THREAD

**Issue by Feldermann** [wahyd4/aria2-ariang-docker#145]
Hi,

I want to let your docker image run on Kubernetes on arm64 but my deployment does not really work.
Do you have a deploymen.yaml file for your package to get it running in Kubernetes cluster?

Regards,
Till

**Comment by wahyd4** [comment]
Hi @Feldermann, I have a running app with the following yaml, please update `persistentVolumeClaim` and `ingress`  to your ones accordingly.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files
spec:
  selector:
    matchLabels:
      app: files
  replicas: 1
  template:
    metadata:
      labels:
        app: files
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: configs-nfs
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-nfs
      containers:
        - name: files
          image: wahyd4/aria2-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: files-port
              protocol: TCP
          env:
            - name: ARIA2_EXTERNAL_PORT
              value: "443"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              subPath: aria
              mountPath: /app/conf
            - name: downloads
              mountPath: /data
            - name: config
              subPath: files/filebrowser.db
              mountPath: /app/filebrowser.db
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: files
  labels:
    app: files
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: files-port
      protocol: TCP
      name: web
  selector:
    app: files

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m    
spec:
  tls:
  - hosts:
    - your-domain.com
    secretName: files-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: files
            port:
              number: 80
```
