### ISSUE TITLE
Docker container not started

### ISSUE THREAD

**Issue by panosru** [wahyd4/aria2-ariang-docker#222]
I'm trying to run this docker container and I'm getting the following output:

```
[INFO] Update uid and gid to 1000:1000
usermod: no changes
[INFO] Give caddy permissions to use low ports
forego                  | starting caddy.1 on port 5000
forego                  | starting filebrowser.1 on port 5100
forego                  | starting aria2c.1 on port 5300
forego                  | starting rclone.1 on port 5600
forego                  | starting newer_version_checker.1 on port 6000
caddy.1                 | [INFO] Run aria2c and ariaNG
caddy.1                 | [INFO] Generate basic auth password for caddy
rclone.1                | [INFO] Skip starting Rclone as it has been disabled
filebrowser.1           | 2022/11/21 15:43:10 No config file used
filebrowser.1           | 2022/11/21 15:43:10 Listening on 127.0.0.1:8080
aria2c.1                | [INFO] Start aria2 with standard mode
forego                  | sending SIGTERM to caddy.1
forego                  | sending SIGTERM to newer_version_checker.1
forego                  | sending SIGTERM to filebrowser.1
forego                  | sending SIGTERM to rclone.1
filebrowser.1           | 2022/11/21 15:43:10 Caught signal terminated: shutting down.
filebrowser.1           | 2022/11/21 15:43:10 accept tcp 127.0.0.1:8080: use of closed network connection
```

I'm not sure filebrowser is shutting down all the time, I followed the guide to the t, but still the container isn't working, could you point me to the right direction?

My tree folder on host looks like this:

![image](https://user-images.githubusercontent.com/400362/203100573-23dbd378-96dd-4123-a87c-2350a779498b.png)

I bind all the appropriate folders as mentioned in the README, for the filebrowser.db, I just run `touch filebrowser.db` in my host and I bind it to the container.

Thanks!

**Comment by panosru** [comment]
Hey @wahyd4, it's a laptop that I'm using as a home server with Intel i5, here are the specs:

![image](https://user-images.githubusercontent.com/400362/203266372-41850bca-8efc-425e-9970-02f0bd3cd629.png)

For docker container deployment I'm using Portainer. I'm using `wahyd4/aria2-ui:latest` image, and the settings are as follows:

![image](https://user-images.githubusercontent.com/400362/203267813-81d0e0c9-10a3-4f1f-b44c-b2336eb32c67.png)

![image](https://user-images.githubusercontent.com/400362/203268356-d7c67085-f9a6-425b-9486-2e34965cfb5b.png)

The network is used to allow nginx reverse proxy to point my domain to this particular container

![image](https://user-images.githubusercontent.com/400362/203268417-c1312b03-56ee-49eb-9b62-4887fdbf0d3a.png)

![image](https://user-images.githubusercontent.com/400362/203268963-0894b978-4809-4d1a-b1d2-3c90dc52431b.png)

![image](https://user-images.githubusercontent.com/400362/203269074-81293621-3a8a-49d8-8200-a5e3466e94c9.png)

![image](https://user-images.githubusercontent.com/400362/203269265-ecb22145-5df1-47c9-acb3-387ffe1472f0.png)

The restart policy is set to `unless stopped`.

Basically, what it does is it provides you with a GUI for docker, it's not different from running the command itself or using docker-compose. I also ran it with docker-compose and I had the exact same result, the YAML file was like this:

```yaml
version: '3'

services:
  aria2:
    image: "wahyd4/aria2-ui:latest"
    container_name: aria2-ui
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '2m'
        max-file: '3'
    expose:
      - 80
      - 443
      - 8080
    cap_add:
      - CHOWN
      - FOWNER
      - MKNOD
      - SETGID
      - SYS_CHROOT
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - NET_RAW
      - SETPCAP
      - NET_BIND_SERVICE
      - SETFCAP
      - SETUID
    privileged: false
    tty: false
    volumes:
      - /home/panosru/Infra/downloader/app/conf:/app/conf
      - /home/panosru/Infra/downloader/app/conf/key:/app/conf/key
      - /home/panosru/Infra/downloader/app/.cache:/app/.cache
      - /home/panosru/Infra/downloader/app/filebrowser.db:/app/filebrowser.db
      - /home/panosru/shared/Downloads:/data
      - /media/portable/Plex:/data/Plex
    environment:
      ENABLE_AUTH: true
      ARIA2_USER: panosru
      ARIA2_PWD: '!@#f$ejefj'
      DOMAIN: "http://**********"
      RPC_SECRET: MYSUPERSECRET123
      ENABLE_RCLONE: false
      ARIA2_SSL: false
      ARIA2_EXTERNAL_PORT: 8080
      PUID: 1000
      PGID: 1000
      CADDY_LOG_LEVEL: ERROR
    networks:
      globalnet:
        ipv4_address: 172.20.0.100
  
networks:
  globalnet:
    external: true
```

I also tried with privileged set to true, and ARIA2_EXTERNAL_PORT set to 80

Thanks!
