### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nalakawula** [wahyd4/aria2-ariang-docker#67]
docker-compose.yaml
```
version: "3.5"
services:
  aria2-ui:
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    environment:
      - ENABLE_AUTH=true
      - ARIA2_USER=myuser
      - ARIA2_PWD=mypass
      - DOMAIN=mydomain.tld
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=myseceret
      - ARIA2_SSL=false
    volumes:
      - ./data:/data
    ports:
      - 10001:80
      - 10002:443
```

docker-compose logs
```
aria2-ui_1  | **** update uid and gid to 1000:1000 ****
aria2-ui_1  | usermod: no changes
aria2-ui_1  | **** give caddy permissions to use low ports ****
aria2-ui_1  | forego        | starting filebrowser.1 on port 5000
aria2-ui_1  | forego        | starting caddy.1 on port 5100
aria2-ui_1  | forego        | starting aria2c.1 on port 5300
aria2-ui_1  | caddy.1       | Run aria2c and ariaNG
aria2-ui_1  | caddy.1       | Using Basic Auth config file 
aria2-ui_1  | aria2c.1      | Start aria2 with standard mode
aria2-ui_1  | caddy.1       | 2019/10/24 04:25:36 decoding certificate metadata: unexpected end of JSON input
aria2-ui_1  | forego        | sending SIGTERM to filebrowser.1
aria2-ui_1  | forego        | sending SIGTERM to aria2c.1
```
