### ISSUE TITLE
[WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set

### ISSUE THREAD

**Issue by nalakawula** [wahyd4/aria2-ariang-docker#71]
The log say that `[WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set`. But i have set it in my compose file.
```
version: "3.5"
services:
  aria2-ui:
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    environment:
      - ENABLE_AUTH=true
      - ARIA2_USER=myuser
      - ARIA2_PWD=mypass
      - DOMAIN=mydomain.tld
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=myseceret
      - ARIA2_SSL=false
    volumes:
      - ./data:/data
    ports:
      - 80:80
      - 443:443
```
