### ISSUE TITLE
Can't enable Letsencrypt auto HTTPS

### ISSUE THREAD

**Issue by LockeJet** [wahyd4/aria2-ariang-docker#81]
## 环境

1. 路由器： OPENWRT；为局域网内的NAS主机设置了端口转发（44381,8081，以及6800）;
2. NAS：Proxmox VE;
2.1 docker-compose.yml:
```
admin@nas:~/docker/aria2$ cat docker-compose.yml
version: "3.5"

networks:
  default:
    external:
      name: nas-bridge
services:
  aria2-ui:
    #restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    container_name: aria2
    environment:
      - ENABLE_AUTH=true
      - ARIA2_USER=admin
      - ARIA2_PWD=passwd
      - ARIA2_EXTERNAL_PORT=8081,44381
      - DOMAIN=https://example.com
    volumes:
      - ./downloads:/data
      - ./certs:/app/conf/key
      - ./conf:/app/conf
      - ./filebrowser.db:/app/filebrowser.db
      #- ./caddy/Caddyfile:/usr/local/caddy/Caddyfile
      #- ./caddy/SecureCaddyfile:/usr/local/caddy/SecureCaddyfile
      #- ./caddy/:/usr/local/caddy
      #- ./certs/:/root/certs/
    ports:
      - 6800:6800
      - 8081:80
      - 44381:443
```
2.2 页面所需要的crt和pem文件都在（ aria2.crt= example.com.pem， aria2.key=example.com.key）。NAS主机上nginx也是用这个pem和key，运行正常。
文件结构如下：
```
admin@nas:~/docker/aria2$ tree
.
├── caddy
│   ├── Caddyfile.bak
│   └── SecureCaddyfile.bak
├── certs
│   ├── aria2.crt
│   ├── aria2.key
│   ├── example.com.key
│   └── example.com.pem
├── conf
│   ├── aria2-bak.conf
│   ├── aria2.session
│   └── key
│       ├── aria2.crt
│       └── aria2.key
├── docker-aria2.sh
├── docker-compose.yml
├── downloads
└── filebrowser.db

6 directories, 12 files
```
2.3 iptables：放行了6800, 8081和44381端口：
```
root@nas:~# iptables -L -n | grep 6800
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 6800 state NEW
root@nas:~# iptables -L -n | grep 8081
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 8000,8080,8071:8079,8081:8089 state NEW
root@nas:~# iptables -L -n | grep 44381
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 44371:44379,44381:44389 state NEW
```
## 问题
运行时却显示：
```
admin@nas:~/docker/aria2$ docker-compose up
Creating aria2 ... done
Attaching to aria2
aria2       | Run aria2c and ariaNG
aria2       | Using Basic Auth config file
aria2       | Start aria2 with standard mode
aria2       | Activating privacy features... 2020/01/29 11:00:06 No config file used
aria2       |
aria2       |
aria2       | Your sites will be served over HTTPS automatically using Let's Encrypt.
aria2       | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
aria2       |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
aria2       | Please enter your email address to signify agreement and to be notified
aria2       | in case of issues. You can leave it blank, but we don't recommend it.
aria2       |   Email address: 2020/01/29 11:00:13 [INFO] [example.com] acme: Obtaining bundled SAN certificate
aria2       | 2020/01/29 11:00:15 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2532163162
aria2       | 2020/01/29 11:00:15 [INFO] [example.com] acme: use tls-alpn-01 solver
aria2       | 2020/01/29 11:00:15 [INFO] [example.com] acme: Trying to solve TLS-ALPN-01
aria2       | 2020/01/29 11:00:32 [example.com] failed to obtain certificate: acme: Error -> One or more domains had a problem:
aria2       | [exaple.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Timeout during connect (likely firewall problem), url:
aria2       | 2020/01/29 11:00:32 [INFO] Unable to deactivated authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2532163162
aria2 exited with code 1
```
请问一下我本机已经有了crt和key文件，还需要Letsencrypt服务器连接我的NAS主机吗？（NAS主机在OPENWRT路由器防火墙后面，外网应该无法连接过来）
作为对比：我在NAS主机运行的nginx服务很正常。
请问问题出在哪里？
谢谢！

**Comment by wahyd4** [comment]
If you want to enable Let's encrypt, then the external port can only and must be `443`. Otherwise, it can't pass the Let's encrypt validation phase.

Besides, the `ARIA2_EXTERNAL_PORT` can only be one port. Actually you only need to expose the main port which should be `443` in this case.

Last, the aria cert and key file are not for `HTTPS` or web browser, they are used for aria data transportation. My recommendation would be using let's encrypt instead. Or you can also try using a universal HTTPS controller. [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) and  [`docker-letsencrypt-nginx-proxy-companion`](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)

There is a working docker-compose example below
```yaml
version: "3.5"
services:
  nginx-proxy:
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    image: jwilder/nginx-proxy:latest
    volumes:
      - ./custom_settings.conf:/etc/nginx/conf.d/custom_settings.conf      
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST="*.xxx.com"
  proxy-letsencrypt:
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL="me@xxx.com"
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  nginx-certs:
  nginx-html:
  nginx-vhost:

```

Then for any application, you just need to add a few environment variables and set the docker container's network to the network above.
```yaml
aria2-ui:
    container_name: aria2-ui
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    networks:
      - gateway_default // This is the network name you created above.
    environment:
      - VIRTUAL_HOST=aa.xxx.com
      - VIRTUAL_PORT=80 
      - LETSENCRYPT_HOST=aa.xxx.com
      - LETSENCRYPT_EMAIL= me@xxx.com
```
